FROM centos:7

MAINTAINER Luis Fernando Gomes <dev@luiscoms.com.br>

ENV LIBEPP libepp-nicbr-1.15

RUN yum update -y\
	&& yum install -y gcc gcc-c++ make xerces-c-devel openssl-devel readline-devel\
	wget\
	&& cd /tmp/ \
	&& wget ftp://ftp.registro.br/pub/libepp-nicbr/${LIBEPP}.tar.gz\
	&& wget ftp://ftp.registro.br/pub/libepp-nicbr/${LIBEPP}.tar.gz.sha1\
	&& sha1sum -c ${LIBEPP}.tar.gz.sha1\
	&& tar xzvf ${LIBEPP}.tar.gz && cd ${LIBEPP}\
	&& ./configure && make && make install\
	&& yum remove -y wget gcc-c++ make\
	&& yum autoremove -y\
	&& yum clean all\
	&& cd - \
	&& rm -rf /tmp/*

WORKDIR /libepp-nicbr

# CMD ['/usr/local/bin/shepp']